# Generated by Django 5.0.4 on 2024-04-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_imagedpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagedPdf',
        ),
    ]
